import { Company } from '@cosuno/api-interfaces';

const companies: Company[] = [
  {
    name: 'Rolfson - Cartwright',
    logo: 'https://www.gravatar.com/avatar/f2e68bb273ff71ee4114fe1596d34cbd?s=128&d=identicon&r=PG',
    specialties: ['Excavation', 'Building', 'Insulation'],
    city: 'Rueckerburgh',
  },
  {
    name: 'Harber - Glover',
    logo: 'https://www.gravatar.com/avatar/350f18aea988c66ba423363063e47cb3?s=128&d=identicon&r=PG',
    specialties: ['Excavation', 'Building', 'Plumbing', 'Electrical'],
    city: 'Beavercreek',
  },
  {
    name: 'Ward - Nicolas',
    logo: 'https://www.gravatar.com/avatar/374441dfa98c147ff5520f3d86757238?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Excavation', 'Building'],
    city: 'Hartmannmouth',
  },
  {
    name: "Feest - O'Connell",
    logo: 'https://www.gravatar.com/avatar/c20524e95b44670ab2bbc423c2e9c4aa?s=128&d=identicon&r=PG',
    specialties: ['Insulation', 'Electrical'],
    city: 'Manntown',
  },
  {
    name: 'Leuschke - Wilderman',
    logo: 'https://www.gravatar.com/avatar/c090fc3f05f9c5034a472701c0f36cb4?s=128&d=identicon&r=PG',
    specialties: ['Excavation', 'Plumbing', 'Building'],
    city: 'West Nikko',
  },
  {
    name: 'Hahn LLC',
    logo: 'https://www.gravatar.com/avatar/ab4c593daaf5e49446cc819bcba47e0a?s=128&d=identicon&r=PG',
    specialties: [
      'Electrical',
      'Building',
      'Excavation',
      'Insulation',
      'Plumbing',
    ],
    city: 'South Mosesland',
  },
  {
    name: 'Schowalter and Sons',
    logo: 'https://www.gravatar.com/avatar/bb9f3a1eac2e1ab86ffcd122ab08720c?s=128&d=identicon&r=PG',
    specialties: ['Electrical'],
    city: 'Rosalindaport',
  },
  {
    name: 'Windler Group',
    logo: 'https://www.gravatar.com/avatar/4475858eced1f6c8f71c6d7ac31681aa?s=128&d=identicon&r=PG',
    specialties: [
      'Building',
      'Electrical',
      'Excavation',
      'Insulation',
      'Plumbing',
    ],
    city: 'South Fanniehaven',
  },
  {
    name: 'Hirthe - Koelpin',
    logo: 'https://www.gravatar.com/avatar/21d579da52393b40912aef350fa02c88?s=128&d=identicon&r=PG',
    specialties: [
      'Electrical',
      'Building',
      'Excavation',
      'Insulation',
      'Plumbing',
    ],
    city: 'South Laverneton',
  },
  {
    name: 'Bahringer Group',
    logo: 'https://www.gravatar.com/avatar/82f13350ab47a869b09f60a8dc71dd8f?s=128&d=identicon&r=PG',
    specialties: ['Electrical'],
    city: 'Carterland',
  },
  {
    name: 'Abshire - Corwin',
    logo: 'https://www.gravatar.com/avatar/d405f98163754ae31763070b48c24630?s=128&d=identicon&r=PG',
    specialties: ['Plumbing', 'Building', 'Insulation'],
    city: 'Lake Merlin',
  },
  {
    name: 'Schoen, Hagenes and Crooks',
    logo: 'https://www.gravatar.com/avatar/20c67c358e66c06f19e1232e75ec422c?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Electrical'],
    city: 'Delray Beach',
  },
  {
    name: 'Leffler LLC',
    logo: 'https://www.gravatar.com/avatar/bb892d9e695e0c6b70941ca5e26fdb3e?s=128&d=identicon&r=PG',
    specialties: [
      'Insulation',
      'Building',
      'Electrical',
      'Plumbing',
      'Excavation',
    ],
    city: 'Asheville',
  },
  {
    name: 'Flatley - Kilback',
    logo: 'https://www.gravatar.com/avatar/46cdf37d20e21c81c97dc46dfa6f73ed?s=128&d=identicon&r=PG',
    specialties: [
      'Plumbing',
      'Insulation',
      'Building',
      'Excavation',
      'Electrical',
    ],
    city: 'VonRuedenfurt',
  },
  {
    name: 'Tromp - Harris',
    logo: 'https://www.gravatar.com/avatar/17052af9436b8334887b128d2f363a83?s=128&d=identicon&r=PG',
    specialties: ['Excavation', 'Insulation', 'Electrical', 'Plumbing'],
    city: 'Powlowskiton',
  },
  {
    name: 'Hirthe - Upton',
    logo: 'https://www.gravatar.com/avatar/8bc47b2c76ec90f148a39d731dd0c607?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Building'],
    city: 'Vellamouth',
  },
  {
    name: 'Skiles and Sons',
    logo: 'https://www.gravatar.com/avatar/bf9a2e28fc4468eaa58cde98a3f8cea0?s=128&d=identicon&r=PG',
    specialties: ['Insulation', 'Excavation', 'Building'],
    city: 'South Guadalupe',
  },
  {
    name: 'Kuhlman and Sons',
    logo: 'https://www.gravatar.com/avatar/d63f8720073f83f9b6401b9afcc8df4a?s=128&d=identicon&r=PG',
    specialties: ['Excavation', 'Building', 'Insulation', 'Plumbing'],
    city: 'Nikolausstad',
  },
  {
    name: 'Adams - Gusikowski',
    logo: 'https://www.gravatar.com/avatar/657d70431367db7cdd8c3b7035cc795c?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Excavation'],
    city: 'Palm Desert',
  },
  {
    name: 'Lehner - Ebert',
    logo: 'https://www.gravatar.com/avatar/e012727b3677aad820d81cb8d090a173?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Excavation', 'Insulation'],
    city: 'West Jovaniport',
  },
  {
    name: 'Mohr and Sons',
    logo: 'https://www.gravatar.com/avatar/5c7fca76344fa404b201a1d892db3e96?s=128&d=identicon&r=PG',
    specialties: ['Insulation', 'Building', 'Excavation'],
    city: 'Mittieland',
  },
  {
    name: 'Prohaska LLC',
    logo: 'https://www.gravatar.com/avatar/96c989a749db8d0f17bed25ccd0e7d9a?s=128&d=identicon&r=PG',
    specialties: ['Insulation', 'Electrical', 'Plumbing', 'Building'],
    city: 'Jupiter',
  },
  {
    name: 'Gibson LLC',
    logo: 'https://www.gravatar.com/avatar/8d0a641d608514e54b1e9649d80d0583?s=128&d=identicon&r=PG',
    specialties: ['Excavation', 'Building'],
    city: 'Victorville',
  },
  {
    name: 'Mosciski Group',
    logo: 'https://www.gravatar.com/avatar/74f62a1ee788c4a1ccbd6a3ac1772d53?s=128&d=identicon&r=PG',
    specialties: ['Building'],
    city: 'Mullerland',
  },
  {
    name: 'Reynolds Group',
    logo: 'https://www.gravatar.com/avatar/c001d6ae27bfb19917797624c4de60c2?s=128&d=identicon&r=PG',
    specialties: ['Building'],
    city: 'South Verlastad',
  },
  {
    name: 'Halvorson, Herzog and Reichert',
    logo: 'https://www.gravatar.com/avatar/97d4f4ec643e01403037ed68698c216a?s=128&d=identicon&r=PG',
    specialties: [
      'Electrical',
      'Plumbing',
      'Excavation',
      'Building',
      'Insulation',
    ],
    city: 'Milford',
  },
  {
    name: 'Simonis - Wiegand',
    logo: 'https://www.gravatar.com/avatar/781e5abadee12589b888f120005a28f1?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Insulation', 'Excavation'],
    city: 'Jeraldmouth',
  },
  {
    name: 'Casper - Dibbert',
    logo: 'https://www.gravatar.com/avatar/e6e5e029121298c2f1d8a6acab792db9?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Electrical', 'Plumbing', 'Excavation'],
    city: 'Sipesshire',
  },
  {
    name: 'Effertz, Fahey and Russel',
    logo: 'https://www.gravatar.com/avatar/47ce3d4528335a2a25825d7881fec6d7?s=128&d=identicon&r=PG',
    specialties: [
      'Insulation',
      'Electrical',
      'Excavation',
      'Plumbing',
      'Building',
    ],
    city: 'New Camren',
  },
  {
    name: 'Beahan - Johnston',
    logo: 'https://www.gravatar.com/avatar/33a1bc6a8e2f58d3584136bed41c9b1f?s=128&d=identicon&r=PG',
    specialties: ['Excavation', 'Insulation', 'Electrical'],
    city: 'Potomac',
  },
  {
    name: 'Macejkovic and Sons',
    logo: 'https://www.gravatar.com/avatar/1be107d3e8c12be54d772d737ee5a2d5?s=128&d=identicon&r=PG',
    specialties: ['Plumbing', 'Electrical'],
    city: 'West Ottilieborough',
  },
  {
    name: 'Roberts LLC',
    logo: 'https://www.gravatar.com/avatar/bfd419ac8dc3895b971847b84b67b1c4?s=128&d=identicon&r=PG',
    specialties: ['Plumbing'],
    city: 'North Albertamouth',
  },
  {
    name: 'Sporer Inc',
    logo: 'https://www.gravatar.com/avatar/639f51088f3ffd3d3f0dbf94cbf336d7?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Insulation'],
    city: 'Champlinview',
  },
  {
    name: 'Torphy - Feil',
    logo: 'https://www.gravatar.com/avatar/8ad06d28d6bb5d81f380cb848bcbc0ca?s=128&d=identicon&r=PG',
    specialties: ['Excavation', 'Electrical'],
    city: 'Deanland',
  },
  {
    name: 'Carter - Towne',
    logo: 'https://www.gravatar.com/avatar/840adb5157f2bf0947a365dc1e9ea241?s=128&d=identicon&r=PG',
    specialties: [
      'Insulation',
      'Plumbing',
      'Excavation',
      'Building',
      'Electrical',
    ],
    city: 'South Jamesonview',
  },
  {
    name: 'Kohler and Sons',
    logo: 'https://www.gravatar.com/avatar/aa33cacafcf8e4daffe1d5e484375b62?s=128&d=identicon&r=PG',
    specialties: ['Plumbing', 'Excavation'],
    city: 'Lake Stanford',
  },
  {
    name: 'Corkery, Weissnat and Rippin',
    logo: 'https://www.gravatar.com/avatar/13b8675be823d76230912bf644aef097?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Building'],
    city: 'East Elysebury',
  },
  {
    name: 'Ritchie Inc',
    logo: 'https://www.gravatar.com/avatar/88934d980a78d11dfb834896c9cb0c92?s=128&d=identicon&r=PG',
    specialties: ['Insulation'],
    city: 'Lake Charitymouth',
  },
  {
    name: 'Runte - Hackett',
    logo: 'https://www.gravatar.com/avatar/89548143b7d2a66496fde682f158cdab?s=128&d=identicon&r=PG',
    specialties: ['Insulation'],
    city: 'Port Janaefurt',
  },
  {
    name: 'Friesen, Corkery and Marquardt',
    logo: 'https://www.gravatar.com/avatar/6332a77d1116a2ddd66dc40d52f1f8d5?s=128&d=identicon&r=PG',
    specialties: ['Building'],
    city: 'East Berenice',
  },
  {
    name: 'Braun LLC',
    logo: 'https://www.gravatar.com/avatar/4de629afbbb4ff7760dc5a2799681e91?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Excavation', 'Plumbing', 'Building'],
    city: 'New Kiaraville',
  },
  {
    name: 'Schuppe, Morar and Waters',
    logo: 'https://www.gravatar.com/avatar/ec020614f75f25ee4331dda3b1b7181c?s=128&d=identicon&r=PG',
    specialties: ['Building'],
    city: 'West Jace',
  },
  {
    name: 'Morissette - Bayer',
    logo: 'https://www.gravatar.com/avatar/22859673664dfb8f3a38c9611e52bc6f?s=128&d=identicon&r=PG',
    specialties: [
      'Excavation',
      'Building',
      'Electrical',
      'Insulation',
      'Plumbing',
    ],
    city: 'New Lesterfort',
  },
  {
    name: 'Watsica LLC',
    logo: 'https://www.gravatar.com/avatar/f7f29838e0890e13c05a6b4d97cafecf?s=128&d=identicon&r=PG',
    specialties: ['Excavation'],
    city: 'Lake Russell',
  },
  {
    name: 'Homenick and Sons',
    logo: 'https://www.gravatar.com/avatar/0803b7ab94ead23be5cac1ab6b1a7b7e?s=128&d=identicon&r=PG',
    specialties: [
      'Electrical',
      'Excavation',
      'Insulation',
      'Building',
      'Plumbing',
    ],
    city: 'New Itzelburgh',
  },
  {
    name: 'Kuphal LLC',
    logo: 'https://www.gravatar.com/avatar/776b8b7fc83f5af1298b2b9501301094?s=128&d=identicon&r=PG',
    specialties: ['Excavation', 'Building', 'Insulation'],
    city: 'East Luis',
  },
  {
    name: 'Crona, Jacobi and Purdy',
    logo: 'https://www.gravatar.com/avatar/cc507b7098b546e0a90496e989b83ede?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Insulation', 'Excavation', 'Plumbing'],
    city: 'Bellevue',
  },
  {
    name: 'Hegmann, Welch and Green',
    logo: 'https://www.gravatar.com/avatar/67a957e5c1a88a1039dd26ea7ea5ee15?s=128&d=identicon&r=PG',
    specialties: [
      'Excavation',
      'Plumbing',
      'Electrical',
      'Building',
      'Insulation',
    ],
    city: 'Lake Beulah',
  },
  {
    name: 'Herman - Runolfsdottir',
    logo: 'https://www.gravatar.com/avatar/3279c7b0faec0eb698f6c8734251e0d4?s=128&d=identicon&r=PG',
    specialties: ['Insulation', 'Plumbing', 'Building'],
    city: 'Antonetteton',
  },
  {
    name: "Konopelski, Gorczany and O'Keefe",
    logo: 'https://www.gravatar.com/avatar/b70cfaf8847bd3509638039ed09dcb72?s=128&d=identicon&r=PG',
    specialties: [
      'Plumbing',
      'Insulation',
      'Electrical',
      'Building',
      'Excavation',
    ],
    city: 'Hahntown',
  },
  {
    name: 'Schroeder and Sons',
    logo: 'https://www.gravatar.com/avatar/67e35d56086b4b217625cedb34395c96?s=128&d=identicon&r=PG',
    specialties: [
      'Building',
      'Electrical',
      'Insulation',
      'Excavation',
      'Plumbing',
    ],
    city: 'Jesuston',
  },
  {
    name: 'Glover and Sons',
    logo: 'https://www.gravatar.com/avatar/bc28384a1f527c79c4bab4b986cd87be?s=128&d=identicon&r=PG',
    specialties: [
      'Excavation',
      'Plumbing',
      'Insulation',
      'Electrical',
      'Building',
    ],
    city: 'Indio',
  },
  {
    name: 'Marks - Cronin',
    logo: 'https://www.gravatar.com/avatar/95d637b7fa8419c17ca08444a3a939b0?s=128&d=identicon&r=PG',
    specialties: ['Plumbing', 'Excavation'],
    city: "O'Haramouth",
  },
  {
    name: 'Nolan, Hand and Braun',
    logo: 'https://www.gravatar.com/avatar/0ff9d07dfdd7a9bb2c4489ed56fc5557?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Excavation', 'Insulation', 'Plumbing'],
    city: 'Lake Napoleon',
  },
  {
    name: 'Brown LLC',
    logo: 'https://www.gravatar.com/avatar/aac5bd13aa3226c305886fa0a6a8d738?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Plumbing', 'Insulation'],
    city: 'Fort Worth',
  },
  {
    name: 'Mohr, Lockman and Botsford',
    logo: 'https://www.gravatar.com/avatar/6968fcb0efd6c26e4f03b0db8c1831ce?s=128&d=identicon&r=PG',
    specialties: ['Insulation', 'Electrical', 'Excavation'],
    city: 'Newellport',
  },
  {
    name: 'Breitenberg - Rowe',
    logo: 'https://www.gravatar.com/avatar/03dab9fcf2a7fbd532fd2c70e184f8a4?s=128&d=identicon&r=PG',
    specialties: [
      'Excavation',
      'Electrical',
      'Insulation',
      'Building',
      'Plumbing',
    ],
    city: 'Bolingbrook',
  },
  {
    name: 'Pfannerstill Inc',
    logo: 'https://www.gravatar.com/avatar/510813d84a15e1e5f74ce3bc7ffa0c42?s=128&d=identicon&r=PG',
    specialties: [
      'Electrical',
      'Excavation',
      'Plumbing',
      'Building',
      'Insulation',
    ],
    city: 'New Maxime',
  },
  {
    name: 'Jenkins Inc',
    logo: 'https://www.gravatar.com/avatar/f7de75b2ef5c422f9627df21da832f79?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Excavation', 'Building'],
    city: 'Lake Nayeli',
  },
  {
    name: 'Waelchi, Jakubowski and Prosacco',
    logo: 'https://www.gravatar.com/avatar/00e0e89835eec104ee1a5a9087bc9a26?s=128&d=identicon&r=PG',
    specialties: ['Insulation', 'Plumbing', 'Excavation'],
    city: 'Cassintown',
  },
  {
    name: 'Schoen, Swaniawski and Trantow',
    logo: 'https://www.gravatar.com/avatar/008291fd740deea1be28fe254352339d?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Insulation', 'Excavation', 'Plumbing'],
    city: 'York',
  },
  {
    name: 'Kunze, Hahn and Rodriguez',
    logo: 'https://www.gravatar.com/avatar/06700b238f54f963dd475af7b9c05e5d?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Excavation', 'Insulation', 'Plumbing'],
    city: 'Dundalk',
  },
  {
    name: 'Prohaska, Weber and Nienow',
    logo: 'https://www.gravatar.com/avatar/09adbac753eccc76c10c748735212435?s=128&d=identicon&r=PG',
    specialties: ['Plumbing', 'Electrical', 'Excavation', 'Building'],
    city: 'Spring',
  },
  {
    name: 'Tremblay, Pagac and Homenick',
    logo: 'https://www.gravatar.com/avatar/fff38a54ae0677627cdf2afa951c0078?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Plumbing'],
    city: 'Kuvalisville',
  },
  {
    name: 'Schinner Group',
    logo: 'https://www.gravatar.com/avatar/b45cdc98bc3bff6b7dcc6d89190430fa?s=128&d=identicon&r=PG',
    specialties: ['Insulation', 'Electrical'],
    city: 'Jonastown',
  },
  {
    name: 'McGlynn, MacGyver and Thompson',
    logo: 'https://www.gravatar.com/avatar/61629db5a4e43173e298621b90820790?s=128&d=identicon&r=PG',
    specialties: ['Excavation', 'Electrical', 'Insulation'],
    city: 'Port Hassan',
  },
  {
    name: 'Marks - Stracke',
    logo: 'https://www.gravatar.com/avatar/3bc48a8382169e7186d26cd5699b7df5?s=128&d=identicon&r=PG',
    specialties: [
      'Building',
      'Insulation',
      'Plumbing',
      'Electrical',
      'Excavation',
    ],
    city: 'Darefort',
  },
  {
    name: 'Klocko LLC',
    logo: 'https://www.gravatar.com/avatar/e2449d288f1ad08bd269b69df5c944e9?s=128&d=identicon&r=PG',
    specialties: ['Excavation', 'Electrical', 'Insulation', 'Building'],
    city: 'West Vivianneport',
  },
  {
    name: 'Vandervort, Dickens and Ebert',
    logo: 'https://www.gravatar.com/avatar/c927dbe81d2f182f81386ec7295cf131?s=128&d=identicon&r=PG',
    specialties: ['Insulation'],
    city: 'Palm Coast',
  },
  {
    name: 'Bauch - Ankunding',
    logo: 'https://www.gravatar.com/avatar/27f00edc0972636f45c9f9cc98837d87?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Excavation'],
    city: 'Lake Jaydon',
  },
  {
    name: 'Weissnat Inc',
    logo: 'https://www.gravatar.com/avatar/8084df9356dfc3b938df7813d5a5e758?s=128&d=identicon&r=PG',
    specialties: ['Excavation', 'Building', 'Plumbing'],
    city: 'Kenyattafurt',
  },
  {
    name: 'Dibbert LLC',
    logo: 'https://www.gravatar.com/avatar/883cacc4391f5c9e74d6cdf969d2b916?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Excavation', 'Insulation'],
    city: 'East Alessandrafort',
  },
  {
    name: 'Zboncak Group',
    logo: 'https://www.gravatar.com/avatar/fe01da8907ef4a9c9c48d9566df8e30c?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Building', 'Excavation'],
    city: 'Kochburgh',
  },
  {
    name: 'Stark LLC',
    logo: 'https://www.gravatar.com/avatar/3ac8191e89f2895e7a2d9c093f8e25a4?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Insulation'],
    city: 'Lake Jaimeshire',
  },
  {
    name: 'Hand - Beahan',
    logo: 'https://www.gravatar.com/avatar/af31f30e674cbc60158b6ca058397a13?s=128&d=identicon&r=PG',
    specialties: [
      'Plumbing',
      'Building',
      'Excavation',
      'Insulation',
      'Electrical',
    ],
    city: 'Hickleville',
  },
  {
    name: 'Fay - Weissnat',
    logo: 'https://www.gravatar.com/avatar/d4d07047d7cfa3e85810901f0271f0d5?s=128&d=identicon&r=PG',
    specialties: ['Excavation', 'Electrical', 'Insulation', 'Plumbing'],
    city: 'Lakewood',
  },
  {
    name: 'Wyman - Douglas',
    logo: 'https://www.gravatar.com/avatar/c59c78d2c074860d29be21fc1807dfb6?s=128&d=identicon&r=PG',
    specialties: ['Excavation'],
    city: 'Lake Jaeden',
  },
  {
    name: 'Sanford, Luettgen and Bogan',
    logo: 'https://www.gravatar.com/avatar/0f645012bcd29f2aa26b7814dff09db6?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Insulation'],
    city: 'Bethesda',
  },
  {
    name: "Nader - D'Amore",
    logo: 'https://www.gravatar.com/avatar/1df51420a7e5e32932a18f35cb93980a?s=128&d=identicon&r=PG',
    specialties: ['Insulation'],
    city: 'Loveland',
  },
  {
    name: 'Pfeffer - Feil',
    logo: 'https://www.gravatar.com/avatar/feec31cbb9496c3dc5c45f4c3f41343c?s=128&d=identicon&r=PG',
    specialties: ['Insulation', 'Excavation'],
    city: 'Springfield',
  },
  {
    name: 'Boyle, Auer and Franey',
    logo: 'https://www.gravatar.com/avatar/dc7746689ad5162f613c487d46d6ce06?s=128&d=identicon&r=PG',
    specialties: ['Insulation'],
    city: 'Blue Springs',
  },
  {
    name: 'Cartwright - Schiller',
    logo: 'https://www.gravatar.com/avatar/1c0ad089eda1da974bb1ccf4a2d1d35f?s=128&d=identicon&r=PG',
    specialties: ['Insulation', 'Plumbing', 'Excavation', 'Electrical'],
    city: 'Kemmerberg',
  },
  {
    name: 'Roberts Inc',
    logo: 'https://www.gravatar.com/avatar/719dc8fb054c8353e43f8a552f2dee55?s=128&d=identicon&r=PG',
    specialties: ['Plumbing'],
    city: 'Carrollton',
  },
  {
    name: 'Grady Group',
    logo: 'https://www.gravatar.com/avatar/ca002ece295c6a7ef818db41c141a03b?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Insulation', 'Electrical'],
    city: 'East Edisonmouth',
  },
  {
    name: 'Connelly, Farrell and Rogahn',
    logo: 'https://www.gravatar.com/avatar/a53c5adaa69bb5535a0884ec08cd2912?s=128&d=identicon&r=PG',
    specialties: ['Insulation', 'Electrical'],
    city: 'Batzview',
  },
  {
    name: 'Pfannerstill Inc',
    logo: 'https://www.gravatar.com/avatar/2adc38dcbaaa8d1d6dbe42c1b179df02?s=128&d=identicon&r=PG',
    specialties: ['Excavation', 'Electrical', 'Plumbing'],
    city: 'Swaniawskiland',
  },
  {
    name: 'Sauer - Kautzer',
    logo: 'https://www.gravatar.com/avatar/33f0b89a18aa5c5abf1a7cefbacf9558?s=128&d=identicon&r=PG',
    specialties: ['Plumbing', 'Excavation', 'Building', 'Insulation'],
    city: 'Heathcotehaven',
  },
  {
    name: 'Konopelski - Miller',
    logo: 'https://www.gravatar.com/avatar/6680b72e959b7a252a9803605cd27b56?s=128&d=identicon&r=PG',
    specialties: [
      'Building',
      'Excavation',
      'Insulation',
      'Electrical',
      'Plumbing',
    ],
    city: 'Tremblayview',
  },
  {
    name: 'Skiles LLC',
    logo: 'https://www.gravatar.com/avatar/cbb8d5c0bd64bcc3a5027e832646a404?s=128&d=identicon&r=PG',
    specialties: ['Excavation'],
    city: 'Flatleyview',
  },
  {
    name: 'Graham - Kemmer',
    logo: 'https://www.gravatar.com/avatar/fdca4e3fbc0e7a46d7446ba6171cdda3?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Insulation'],
    city: 'Belleville',
  },
  {
    name: "O'Hara, Witting and Waelchi",
    logo: 'https://www.gravatar.com/avatar/b0f0db0204740b847ad81ee04948e5f4?s=128&d=identicon&r=PG',
    specialties: ['Insulation', 'Electrical', 'Plumbing'],
    city: 'West Davin',
  },
  {
    name: 'Rice - Rippin',
    logo: 'https://www.gravatar.com/avatar/cb5f8b0f3faad1da27e2c8226e3b0587?s=128&d=identicon&r=PG',
    specialties: ['Insulation', 'Plumbing', 'Excavation', 'Electrical'],
    city: 'Gusikowskifurt',
  },
  {
    name: 'Robel, Veum and Hickle',
    logo: 'https://www.gravatar.com/avatar/020730a3ed96413f76260f45779604bf?s=128&d=identicon&r=PG',
    specialties: [
      'Building',
      'Electrical',
      'Plumbing',
      'Insulation',
      'Excavation',
    ],
    city: 'Gottliebland',
  },
  {
    name: 'Morissette, Wehner and Marvin',
    logo: 'https://www.gravatar.com/avatar/94557f7e77a68997a194f45a90bd5750?s=128&d=identicon&r=PG',
    specialties: ['Excavation', 'Electrical'],
    city: 'Kuhnbury',
  },
  {
    name: 'Kemmer - Kshlerin',
    logo: 'https://www.gravatar.com/avatar/d80f5264301530144f3075abca5f85fa?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Electrical', 'Insulation', 'Excavation'],
    city: 'Mrazfurt',
  },
  {
    name: 'Walsh Group',
    logo: 'https://www.gravatar.com/avatar/f5a11b3a077b196f12f4a9e4fbeea106?s=128&d=identicon&r=PG',
    specialties: ['Plumbing', 'Excavation', 'Building'],
    city: 'East Juniormouth',
  },
  {
    name: 'White, Schowalter and Mraz',
    logo: 'https://www.gravatar.com/avatar/6f24529266f41067da5e6f0736828401?s=128&d=identicon&r=PG',
    specialties: ['Building'],
    city: 'Lake Nathan',
  },
  {
    name: 'McDermott, Maggio and Bosco',
    logo: 'https://www.gravatar.com/avatar/316cf8476e45487a01ec107b45d23fad?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Electrical'],
    city: 'Brookline',
  },
  {
    name: 'Parisian - Koelpin',
    logo: 'https://www.gravatar.com/avatar/5b73cb3900170a3f4a80a79e0a418eac?s=128&d=identicon&r=PG',
    specialties: [
      'Insulation',
      'Building',
      'Plumbing',
      'Excavation',
      'Electrical',
    ],
    city: 'Farrellmouth',
  },
  {
    name: 'Nienow - Wilderman',
    logo: 'https://www.gravatar.com/avatar/194b6e0a645cc8282167347e669aaaaf?s=128&d=identicon&r=PG',
    specialties: [
      'Electrical',
      'Building',
      'Excavation',
      'Plumbing',
      'Insulation',
    ],
    city: 'Hoppeport',
  },
  {
    name: 'Hyatt - Crona',
    logo: 'https://www.gravatar.com/avatar/aeea50981252437dc59497af78c1b275?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Excavation', 'Plumbing', 'Electrical'],
    city: 'Silasshire',
  },
  {
    name: 'Klocko, Nolan and Hirthe',
    logo: 'https://www.gravatar.com/avatar/6a9ff4a4c40b874a66abebd14b2a74fe?s=128&d=identicon&r=PG',
    specialties: [
      'Building',
      'Excavation',
      'Electrical',
      'Plumbing',
      'Insulation',
    ],
    city: 'Jerdeland',
  },
  {
    name: "O'Kon - Schaefer",
    logo: 'https://www.gravatar.com/avatar/a5b55e649b615c7416fcdf629c2b87f1?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Excavation'],
    city: 'Port Kaelynfort',
  },
  {
    name: 'Lubowitz, Buckridge and Kutch',
    logo: 'https://www.gravatar.com/avatar/7dfde6be5cd0a970736e1ba2b6e00bf7?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Plumbing'],
    city: 'Anchorage',
  },
  {
    name: 'Johnston Group',
    logo: 'https://www.gravatar.com/avatar/baa1e63dc95b44c0d345bd0b7ab302f7?s=128&d=identicon&r=PG',
    specialties: [
      'Plumbing',
      'Building',
      'Insulation',
      'Electrical',
      'Excavation',
    ],
    city: 'Bednartown',
  },
  {
    name: 'King, Lubowitz and Reichert',
    logo: 'https://www.gravatar.com/avatar/edbb5ae32bfe9efe76aa073bed06bd4d?s=128&d=identicon&r=PG',
    specialties: ['Insulation'],
    city: 'Huntsville',
  },
  {
    name: 'Cummings and Sons',
    logo: 'https://www.gravatar.com/avatar/191cbadb4bf761fadfe5f78c1393d5c4?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Electrical'],
    city: 'Columbus',
  },
  {
    name: 'Reichel, Bartell and Green',
    logo: 'https://www.gravatar.com/avatar/7ec10e3a64e6784e9afadf9b97fbd798?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Electrical'],
    city: 'Albertoshire',
  },
  {
    name: 'Weimann - Dach',
    logo: 'https://www.gravatar.com/avatar/a98d0c03a7a0b3add3275a9f33f88e80?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Plumbing', 'Excavation'],
    city: 'Stockton',
  },
  {
    name: 'Bergnaum, Kuphal and Weber',
    logo: 'https://www.gravatar.com/avatar/9e455344191d77a6639eb2d43588fedb?s=128&d=identicon&r=PG',
    specialties: ['Electrical'],
    city: 'New Katlynfurt',
  },
  {
    name: 'Pfannerstill LLC',
    logo: 'https://www.gravatar.com/avatar/f79bde109b9ce43f41a3910b6603f85a?s=128&d=identicon&r=PG',
    specialties: [
      'Excavation',
      'Building',
      'Electrical',
      'Plumbing',
      'Insulation',
    ],
    city: 'San Bernardino',
  },
  {
    name: 'Fritsch - Wolff',
    logo: 'https://www.gravatar.com/avatar/e03e00b00f310dbbeb5b3a9d553434f8?s=128&d=identicon&r=PG',
    specialties: [
      'Building',
      'Plumbing',
      'Excavation',
      'Insulation',
      'Electrical',
    ],
    city: 'Etheltown',
  },
  {
    name: 'Gusikowski Group',
    logo: 'https://www.gravatar.com/avatar/2340b1cb84cbdfbbd3dc779a1d5bbe0f?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Excavation', 'Insulation'],
    city: 'Casa Grande',
  },
  {
    name: 'Moen LLC',
    logo: 'https://www.gravatar.com/avatar/488a3d56e7d39c012b73538462a79f5c?s=128&d=identicon&r=PG',
    specialties: ['Insulation'],
    city: 'Caterinaborough',
  },
  {
    name: 'Hoeger Inc',
    logo: 'https://www.gravatar.com/avatar/4c88896e3ecdc750ab49c399060165a5?s=128&d=identicon&r=PG',
    specialties: ['Plumbing', 'Building'],
    city: 'Columbia',
  },
  {
    name: 'Reynolds, Haag and Ruecker',
    logo: 'https://www.gravatar.com/avatar/4dd371ab3e1cd6b6742055ac6dcd0407?s=128&d=identicon&r=PG',
    specialties: [
      'Electrical',
      'Plumbing',
      'Building',
      'Excavation',
      'Insulation',
    ],
    city: 'West Javon',
  },
  {
    name: 'Stamm, Legros and Powlowski',
    logo: 'https://www.gravatar.com/avatar/1643f5651c94e8f9d444a36fe3ca219d?s=128&d=identicon&r=PG',
    specialties: ['Plumbing'],
    city: 'East Corine',
  },
  {
    name: 'Mraz LLC',
    logo: 'https://www.gravatar.com/avatar/46ea53c74850a2b5765f5bdc12f3991d?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Plumbing', 'Excavation', 'Electrical'],
    city: 'East Providence',
  },
  {
    name: 'Macejkovic, Blick and Weissnat',
    logo: 'https://www.gravatar.com/avatar/5095f006ea997f7d9669e0e0bcdeedbf?s=128&d=identicon&r=PG',
    specialties: [
      'Building',
      'Plumbing',
      'Electrical',
      'Insulation',
      'Excavation',
    ],
    city: 'Killeen',
  },
  {
    name: 'Mohr, Raynor and Harris',
    logo: 'https://www.gravatar.com/avatar/e09b82a7e2c7dc3bea72e9db436fd5a3?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Insulation', 'Plumbing', 'Electrical'],
    city: 'Lake Penelope',
  },
  {
    name: 'Kozey - Hammes',
    logo: 'https://www.gravatar.com/avatar/1803350f9a82cd5301e39a5b4294c1ba?s=128&d=identicon&r=PG',
    specialties: ['Plumbing', 'Insulation', 'Electrical'],
    city: 'Port Jayden',
  },
  {
    name: 'Konopelski LLC',
    logo: 'https://www.gravatar.com/avatar/7bb740cd6e5f0e9f003b08baa1eda928?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Plumbing', 'Excavation', 'Electrical'],
    city: 'Alfonsoborough',
  },
  {
    name: 'Runolfsdottir Inc',
    logo: 'https://www.gravatar.com/avatar/2b044ef61756c20fb860c739a15a9ee0?s=128&d=identicon&r=PG',
    specialties: ['Insulation', 'Excavation', 'Electrical', 'Building'],
    city: 'Downey',
  },
  {
    name: 'Hahn Group',
    logo: 'https://www.gravatar.com/avatar/5f4083c71a565958ba822ccd5589546f?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Excavation', 'Electrical'],
    city: 'Traceyhaven',
  },
  {
    name: 'Kemmer - Schultz',
    logo: 'https://www.gravatar.com/avatar/24570aa8f63bdc9a7bc84e7a431a1985?s=128&d=identicon&r=PG',
    specialties: ['Plumbing', 'Electrical', 'Building', 'Excavation'],
    city: 'South Hermann',
  },
  {
    name: 'Lowe LLC',
    logo: 'https://www.gravatar.com/avatar/27ea8e6d5845f6f3efa7b63f413ac178?s=128&d=identicon&r=PG',
    specialties: ['Excavation'],
    city: 'Arnoldoborough',
  },
  {
    name: 'Nikolaus and Sons',
    logo: 'https://www.gravatar.com/avatar/e43ff8989342cdd0d37babe703eb1fe9?s=128&d=identicon&r=PG',
    specialties: [
      'Plumbing',
      'Insulation',
      'Electrical',
      'Excavation',
      'Building',
    ],
    city: 'Port Beaustad',
  },
  {
    name: 'Simonis, Monahan and Muller',
    logo: 'https://www.gravatar.com/avatar/cbf4c91dc5e86286f72899e9ddfffb28?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Insulation', 'Plumbing'],
    city: 'Belleville',
  },
  {
    name: 'Baumbach Group',
    logo: 'https://www.gravatar.com/avatar/c75b96d3e2bc4e636dbe311a87462de7?s=128&d=identicon&r=PG',
    specialties: ['Plumbing'],
    city: 'Plainfield',
  },
  {
    name: 'Cremin and Sons',
    logo: 'https://www.gravatar.com/avatar/20f602817654147cd0591b83702b2be0?s=128&d=identicon&r=PG',
    specialties: ['Insulation', 'Excavation'],
    city: 'Port Bernardo',
  },
  {
    name: 'Wilkinson Inc',
    logo: 'https://www.gravatar.com/avatar/36689a9d24bcf2cfac97ea2d8d747525?s=128&d=identicon&r=PG',
    specialties: ['Insulation', 'Electrical', 'Excavation'],
    city: 'East Orange',
  },
  {
    name: 'McDermott Inc',
    logo: 'https://www.gravatar.com/avatar/a373bc6b7d461dc75405e2d65fcf3641?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Insulation', 'Building'],
    city: 'Noelfort',
  },
  {
    name: 'Gaylord - Bergstrom',
    logo: 'https://www.gravatar.com/avatar/c8c5ee0151c180851941a2ab43b52043?s=128&d=identicon&r=PG',
    specialties: ['Insulation'],
    city: 'Woodland',
  },
  {
    name: 'Lockman - Roob',
    logo: 'https://www.gravatar.com/avatar/17430fb462c23696e0f7c9c69215d17d?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Insulation', 'Plumbing', 'Excavation'],
    city: 'Cassieland',
  },
  {
    name: 'Mosciski Inc',
    logo: 'https://www.gravatar.com/avatar/001d87949e9b33b8fdf6c186a3b48d18?s=128&d=identicon&r=PG',
    specialties: ['Plumbing', 'Excavation', 'Building', 'Electrical'],
    city: 'Hazelshire',
  },
  {
    name: 'Purdy LLC',
    logo: 'https://www.gravatar.com/avatar/85498cddda25c480b32d8a4444b6af1b?s=128&d=identicon&r=PG',
    specialties: ['Plumbing', 'Insulation', 'Electrical'],
    city: 'Riverside',
  },
  {
    name: 'Bosco - Cronin',
    logo: 'https://www.gravatar.com/avatar/bd8339086aa90fb25318bd4cf620154f?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Insulation', 'Plumbing', 'Excavation'],
    city: 'Hellerstad',
  },
  {
    name: 'Reilly - Barton',
    logo: 'https://www.gravatar.com/avatar/ac25cba01916fcf4df8b440762c4720e?s=128&d=identicon&r=PG',
    specialties: ['Insulation', 'Excavation', 'Electrical'],
    city: 'East Cedrick',
  },
  {
    name: 'Heathcote Group',
    logo: 'https://www.gravatar.com/avatar/84a1e1abeb746bbb1db80b2f6ee5401b?s=128&d=identicon&r=PG',
    specialties: ['Plumbing', 'Excavation'],
    city: 'Pagacmouth',
  },
  {
    name: 'Mraz Group',
    logo: 'https://www.gravatar.com/avatar/c61a243bfb8575e059aeabc5301b0495?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Excavation', 'Electrical'],
    city: 'Port Piperberg',
  },
  {
    name: 'Langosh, Metz and Kris',
    logo: 'https://www.gravatar.com/avatar/d5eb47404bb6ed36cbfbf165057fb4d9?s=128&d=identicon&r=PG',
    specialties: ['Plumbing', 'Building'],
    city: 'Port Kyleberg',
  },
  {
    name: 'Turner LLC',
    logo: 'https://www.gravatar.com/avatar/628524f7f67b4a5e7a7e9af723036fc5?s=128&d=identicon&r=PG',
    specialties: [
      'Plumbing',
      'Insulation',
      'Electrical',
      'Building',
      'Excavation',
    ],
    city: 'Rahsaanport',
  },
  {
    name: 'Schroeder - Toy',
    logo: 'https://www.gravatar.com/avatar/4df0a03cff67a6402a0432fe3f38d45e?s=128&d=identicon&r=PG',
    specialties: ['Plumbing', 'Excavation'],
    city: 'Kevonburgh',
  },
  {
    name: 'Kessler - Zulauf',
    logo: 'https://www.gravatar.com/avatar/f2b1ee0cb198efefc3676fbe02189247?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Plumbing', 'Insulation'],
    city: 'Beierville',
  },
  {
    name: 'Cole - Schmeler',
    logo: 'https://www.gravatar.com/avatar/77fd089c80766bfed07443f3cc9129fd?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Plumbing', 'Excavation'],
    city: 'West Jared',
  },
  {
    name: 'Schmidt Group',
    logo: 'https://www.gravatar.com/avatar/b41388b7194698526977164c1767e039?s=128&d=identicon&r=PG',
    specialties: [
      'Plumbing',
      'Excavation',
      'Electrical',
      'Building',
      'Insulation',
    ],
    city: 'Augustinemouth',
  },
  {
    name: 'Stark, Tillman and Feeney',
    logo: 'https://www.gravatar.com/avatar/d7152029143be5e9acadfac632abac12?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Insulation', 'Excavation', 'Plumbing'],
    city: 'New Wilhelmine',
  },
  {
    name: 'Heathcote - Wiegand',
    logo: 'https://www.gravatar.com/avatar/b3ddcbd8c088a85da738f987373e45fc?s=128&d=identicon&r=PG',
    specialties: ['Building'],
    city: 'Baumbachberg',
  },
  {
    name: 'Reichel Inc',
    logo: 'https://www.gravatar.com/avatar/ae6604ce4bfa4816d7ca2c0b28d3d644?s=128&d=identicon&r=PG',
    specialties: ['Insulation', 'Excavation'],
    city: 'Oshkosh',
  },
  {
    name: 'Becker, Osinski and Mann',
    logo: 'https://www.gravatar.com/avatar/d39c6e2084ce8a64eee3839a8f7a6515?s=128&d=identicon&r=PG',
    specialties: [
      'Insulation',
      'Plumbing',
      'Excavation',
      'Electrical',
      'Building',
    ],
    city: 'New Vivianefort',
  },
  {
    name: 'Terry - Maggio',
    logo: 'https://www.gravatar.com/avatar/4958af93856dec9a57e43ab3b92b32d9?s=128&d=identicon&r=PG',
    specialties: ['Insulation'],
    city: 'Lake Elouise',
  },
  {
    name: 'Ruecker - Hessel',
    logo: 'https://www.gravatar.com/avatar/78a894bba194ec06a9881c838c029166?s=128&d=identicon&r=PG',
    specialties: ['Excavation'],
    city: 'New Bonitachester',
  },
  {
    name: 'Collier, Mayer and Schaefer',
    logo: 'https://www.gravatar.com/avatar/e348783eebcf7f8450bb143e1569c59e?s=128&d=identicon&r=PG',
    specialties: [
      'Excavation',
      'Insulation',
      'Plumbing',
      'Building',
      'Electrical',
    ],
    city: 'Bradborough',
  },
  {
    name: 'Franecki and Sons',
    logo: 'https://www.gravatar.com/avatar/5cbf1e74d26d54686459fc8eae711cd2?s=128&d=identicon&r=PG',
    specialties: ['Plumbing'],
    city: 'East Wilfredo',
  },
  {
    name: 'Abernathy - Gorczany',
    logo: 'https://www.gravatar.com/avatar/fd156363da977cbbc8a25d561c8b56a4?s=128&d=identicon&r=PG',
    specialties: [
      'Plumbing',
      'Excavation',
      'Building',
      'Insulation',
      'Electrical',
    ],
    city: 'South Joaquinland',
  },
  {
    name: 'Stoltenberg - Schuppe',
    logo: 'https://www.gravatar.com/avatar/1998e2ef5073e4e427ba01b1064918d8?s=128&d=identicon&r=PG',
    specialties: [
      'Insulation',
      'Building',
      'Plumbing',
      'Electrical',
      'Excavation',
    ],
    city: 'Reeceland',
  },
  {
    name: 'Lemke LLC',
    logo: 'https://www.gravatar.com/avatar/5f5d86a1aadf9dda7f34b7e9fa5503a4?s=128&d=identicon&r=PG',
    specialties: ['Plumbing', 'Building', 'Electrical', 'Insulation'],
    city: 'Port Nick',
  },
  {
    name: 'Reichel, Cummerata and Bogisich',
    logo: 'https://www.gravatar.com/avatar/d6ec81f4c25cee86f9231de1365b5d3a?s=128&d=identicon&r=PG',
    specialties: ['Electrical'],
    city: 'South Alizebury',
  },
  {
    name: 'Barton and Sons',
    logo: 'https://www.gravatar.com/avatar/81ff32fb179b4b6d302dee1f5bd630a6?s=128&d=identicon&r=PG',
    specialties: [
      'Plumbing',
      'Insulation',
      'Excavation',
      'Electrical',
      'Building',
    ],
    city: 'New Krista',
  },
  {
    name: 'Parker, Johnson and Bechtelar',
    logo: 'https://www.gravatar.com/avatar/89a16c41c6c50e7a0d3b2052f7561aa4?s=128&d=identicon&r=PG',
    specialties: [
      'Insulation',
      'Building',
      'Plumbing',
      'Electrical',
      'Excavation',
    ],
    city: 'New Nickolasville',
  },
  {
    name: 'Carter - Robel',
    logo: 'https://www.gravatar.com/avatar/502887ec8c131fc8f00cd6c9eb4513aa?s=128&d=identicon&r=PG',
    specialties: [
      'Electrical',
      'Excavation',
      'Insulation',
      'Building',
      'Plumbing',
    ],
    city: 'Midwest City',
  },
  {
    name: 'Kessler and Sons',
    logo: 'https://www.gravatar.com/avatar/8e2a46332e04b683ee84e19df37b71dc?s=128&d=identicon&r=PG',
    specialties: [
      'Plumbing',
      'Excavation',
      'Building',
      'Insulation',
      'Electrical',
    ],
    city: 'Nathenborough',
  },
  {
    name: 'Ritchie, Spinka and Altenwerth',
    logo: 'https://www.gravatar.com/avatar/5a6f0ee4991337683f36e71481909957?s=128&d=identicon&r=PG',
    specialties: ['Insulation'],
    city: 'Lakewood',
  },
  {
    name: 'Shields - Cartwright',
    logo: 'https://www.gravatar.com/avatar/346da97dd10fc70394d41f846b060c3e?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Building'],
    city: 'New Jarred',
  },
  {
    name: 'Hayes, Rodriguez and Koss',
    logo: 'https://www.gravatar.com/avatar/a90a37117eacb7e097b8c9578286d226?s=128&d=identicon&r=PG',
    specialties: ['Plumbing', 'Excavation', 'Building', 'Insulation'],
    city: 'Middletown',
  },
  {
    name: 'Sanford, Bahringer and Streich',
    logo: 'https://www.gravatar.com/avatar/3a71cd6aebeb6c272a5ef68458936a2a?s=128&d=identicon&r=PG',
    specialties: ['Excavation', 'Insulation', 'Plumbing', 'Building'],
    city: 'Haverhill',
  },
  {
    name: 'Kihn - Rowe',
    logo: 'https://www.gravatar.com/avatar/19be798c7f007c001684c20dc469eede?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Insulation', 'Electrical', 'Excavation'],
    city: 'Constantinmouth',
  },
  {
    name: 'Stiedemann, Gaylord and Kuhic',
    logo: 'https://www.gravatar.com/avatar/af837d0531ea436b44183243213afbfc?s=128&d=identicon&r=PG',
    specialties: ['Building'],
    city: 'Virginia Beach',
  },
  {
    name: 'Hilll - Abernathy',
    logo: 'https://www.gravatar.com/avatar/6ea9f5521429ed1b377af104f2b38098?s=128&d=identicon&r=PG',
    specialties: ['Plumbing', 'Building'],
    city: 'Mireyaport',
  },
  {
    name: 'Reilly - Deckow',
    logo: 'https://www.gravatar.com/avatar/b67772ea3a0c77b92b5cb52b6e85340f?s=128&d=identicon&r=PG',
    specialties: ['Plumbing', 'Electrical', 'Insulation', 'Building'],
    city: 'Wymanton',
  },
  {
    name: 'Hagenes, Botsford and Zulauf',
    logo: 'https://www.gravatar.com/avatar/5a23425734d08c7b3b27e3013c12ce57?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Excavation'],
    city: 'South Arielview',
  },
  {
    name: 'Prosacco and Sons',
    logo: 'https://www.gravatar.com/avatar/07beeea5d6f00131a81b477c70c89d6c?s=128&d=identicon&r=PG',
    specialties: ['Plumbing', 'Excavation', 'Building', 'Electrical'],
    city: 'Hayesstad',
  },
  {
    name: 'DuBuque, Kunze and Effertz',
    logo: 'https://www.gravatar.com/avatar/2c76641848da0cde6bea9944c2b3d8e8?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Insulation'],
    city: 'Anastasiaport',
  },
  {
    name: 'Kassulke and Sons',
    logo: 'https://www.gravatar.com/avatar/c19023107ffd3c4ee1d7909cc6c61160?s=128&d=identicon&r=PG',
    specialties: ['Excavation', 'Insulation', 'Plumbing', 'Electrical'],
    city: 'Barrettton',
  },
  {
    name: 'Jacobs Group',
    logo: 'https://www.gravatar.com/avatar/e0fb83abf07cbcc0c9016cabbb5805c4?s=128&d=identicon&r=PG',
    specialties: ['Plumbing', 'Building', 'Insulation'],
    city: 'Metairie',
  },
  {
    name: 'Kunde, Emmerich and Considine',
    logo: 'https://www.gravatar.com/avatar/1362905cbf778292caff15c85d98b9e0?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Insulation', 'Electrical'],
    city: 'Dickinsonchester',
  },
  {
    name: 'Donnelly and Sons',
    logo: 'https://www.gravatar.com/avatar/1f16c626226bf3a107f0a382dd34de65?s=128&d=identicon&r=PG',
    specialties: ['Plumbing', 'Electrical', 'Insulation'],
    city: 'South Colin',
  },
  {
    name: 'Crona Group',
    logo: 'https://www.gravatar.com/avatar/14fb183fe3d4dcc2ba251d49dd8d7ea5?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Insulation', 'Electrical'],
    city: 'Port Justinaport',
  },
  {
    name: "Friesen - O'Conner",
    logo: 'https://www.gravatar.com/avatar/2b4c337f44fa4bd35e9267c3677587b4?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Plumbing', 'Excavation', 'Insulation'],
    city: 'Audreyton',
  },
  {
    name: 'Hirthe - Ebert',
    logo: 'https://www.gravatar.com/avatar/122d6580fc44cb5ead6059c508344f21?s=128&d=identicon&r=PG',
    specialties: ['Excavation', 'Building', 'Plumbing'],
    city: 'Sanfordside',
  },
  {
    name: 'Stiedemann, Huels and Muller',
    logo: 'https://www.gravatar.com/avatar/33d3631531825b2aa4a4c9dbb6998464?s=128&d=identicon&r=PG',
    specialties: [
      'Plumbing',
      'Insulation',
      'Building',
      'Electrical',
      'Excavation',
    ],
    city: 'Youngstown',
  },
  {
    name: 'Haag, Hills and Schneider',
    logo: 'https://www.gravatar.com/avatar/8b4b5e4855d38548f3655734bb7b15fa?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Plumbing', 'Excavation', 'Building'],
    city: 'Jayshire',
  },
  {
    name: 'Renner, Lindgren and Glover',
    logo: 'https://www.gravatar.com/avatar/30fe9f0b9cebfbbd76b0d0f514a0f705?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Excavation'],
    city: 'Deltona',
  },
  {
    name: 'Hayes - Zieme',
    logo: 'https://www.gravatar.com/avatar/1836ac39eaed068270a7b4efcf227770?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Insulation'],
    city: 'New Kennith',
  },
  {
    name: 'Johnson and Sons',
    logo: 'https://www.gravatar.com/avatar/2e298251394491e7326a8755c5485060?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Building', 'Insulation'],
    city: 'Schmidtton',
  },
  {
    name: 'Schulist and Sons',
    logo: 'https://www.gravatar.com/avatar/843353a3982133c5b4d99890575ae009?s=128&d=identicon&r=PG',
    specialties: ['Excavation', 'Plumbing'],
    city: 'West Olehaven',
  },
  {
    name: 'Corwin - Murphy',
    logo: 'https://www.gravatar.com/avatar/efc253a2f2af339f0523ed6cf79574a9?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Plumbing'],
    city: 'South Serenaburgh',
  },
  {
    name: 'Blick Group',
    logo: 'https://www.gravatar.com/avatar/b40858dbb0a5126554e54426490ae795?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Insulation'],
    city: 'Port Irwin',
  },
  {
    name: 'Paucek, Franey and Reilly',
    logo: 'https://www.gravatar.com/avatar/7e46b7af8582d0007b496105211fec4e?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Building'],
    city: 'Delfinashire',
  },
  {
    name: 'Kiehn, Padberg and Kuhic',
    logo: 'https://www.gravatar.com/avatar/5176d64e4f9b789ccc79a51010708332?s=128&d=identicon&r=PG',
    specialties: ['Plumbing', 'Excavation', 'Insulation'],
    city: 'New Sydneestad',
  },
  {
    name: 'Ortiz, Smith and Pfeffer',
    logo: 'https://www.gravatar.com/avatar/6f9ded75580aea8529404615c179d22c?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Insulation', 'Plumbing', 'Excavation'],
    city: 'Lake Everetteville',
  },
  {
    name: 'Price, Wiegand and Klein',
    logo: 'https://www.gravatar.com/avatar/5c720d129f38411690117b9b2d6479e6?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Electrical', 'Plumbing', 'Excavation'],
    city: 'Colemouth',
  },
  {
    name: 'Kautzer, Pouros and Kohler',
    logo: 'https://www.gravatar.com/avatar/7978fee7c8b0a4a12cafac1d5315c094?s=128&d=identicon&r=PG',
    specialties: ['Excavation'],
    city: 'Medhurstport',
  },
  {
    name: 'Mohr, Weimann and Bergnaum',
    logo: 'https://www.gravatar.com/avatar/c3ac14fd0906a62dab5e05e2a4c4a0cf?s=128&d=identicon&r=PG',
    specialties: ['Excavation', 'Insulation', 'Building', 'Electrical'],
    city: 'East Marquesbury',
  },
  {
    name: 'Harvey, Marvin and Cronin',
    logo: 'https://www.gravatar.com/avatar/a888ab94f4acbf63352658042f7739fb?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Insulation', 'Excavation', 'Plumbing'],
    city: 'Emmychester',
  },
  {
    name: 'Heidenreich, Maggio and Rath',
    logo: 'https://www.gravatar.com/avatar/7bf0150d869d2441d7ae78b5b377bcd3?s=128&d=identicon&r=PG',
    specialties: ['Plumbing', 'Electrical', 'Excavation', 'Insulation'],
    city: 'Lake Odie',
  },
  {
    name: 'Hansen Group',
    logo: 'https://www.gravatar.com/avatar/4ae72eb8ffc6367ddc2217b2c4155998?s=128&d=identicon&r=PG',
    specialties: ['Excavation', 'Insulation', 'Plumbing', 'Building'],
    city: 'Blickchester',
  },
  {
    name: 'Hudson, Price and Kilback',
    logo: 'https://www.gravatar.com/avatar/3943a3e24841217e88a8f2d8e1d92df3?s=128&d=identicon&r=PG',
    specialties: ['Plumbing', 'Insulation'],
    city: 'Kariville',
  },
  {
    name: 'Bayer - Weber',
    logo: 'https://www.gravatar.com/avatar/25f3ed1bc27454bece52a8f7676d50ff?s=128&d=identicon&r=PG',
    specialties: ['Electrical', 'Excavation', 'Building'],
    city: 'Portsmouth',
  },
  {
    name: 'Ortiz - Hermiston',
    logo: 'https://www.gravatar.com/avatar/f3b793d149d1b34c17aa6d36775f4e33?s=128&d=identicon&r=PG',
    specialties: ['Building', 'Insulation', 'Electrical', 'Excavation'],
    city: 'South Jaylinport',
  },
];
export default companies;
